title: MentaliOS
author:
  name: TetroLabs
  
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  MentaliOS
    
header_pages:
- README.md
- download.md
  
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
